//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int B_Id { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<int> Sr_No { get; set; }
        public string Medicien_Name { get; set; }
        public string Quantity { get; set; }
        public string Unit { get; set; }
        public string Price { get; set; }
        public int Sa_Id { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
